export const banks = [
    { value: "Airtel Payments Bank", label: "Airtel Payments Bank" },
    { value: "American Express Banking Corporation", label: "American Express Banking Corporation" },
    { value: "Andhra Pradesh Grameena Vikas Bank", label: "Andhra Pradesh Grameena Vikas Bank" },
    { value: "Andhra Pragathi Grameena Bank", label: "Andhra Pragathi Grameena Bank" },
    { value: "Aryavart Bank", label: "Aryavart Bank" },
    { value: "Assam Gramin Vikash Bank", label: "Assam Gramin Vikash Bank" },
    { value: "Au Small Finance Bank", label: "Au Small Finance Bank" },
    { value: "Axis Bank", label: "Axis Bank" },
    { value: "Bandhan Bank", label: "Bandhan Bank" },
    { value: "Bangiya Gramin Vikash Bank", label: "Bangiya Gramin Vikash Bank" },
    { value: "Bank of America", label: "Bank of America" },
    { value: "Bank of Baroda", label: "Bank of Baroda (BOB)" },
    { value: "Bank of India", label: "Bank of India (BOI)" },
    { value: "Bank of Maharashtra", label: "Bank of Maharashtra" },
    { value: "Barclays Bank", label: "Barclays Bank" },
    { value: "Baroda Gujarat Gramin Bank", label: "Baroda Gujarat Gramin Bank" },
    { value: "Baroda Rajasthan Kshetriya Gramin Bank", label: "Baroda Rajasthan Kshetriya Gramin Bank" },
    { value: "Baroda UP Bank", label: "Baroda UP Bank" },
    { value: "BNP Paribas", label: "BNP Paribas" },
    { value: "Canara Bank", label: "Canara Bank" },
    { value: "Capital Small Finance Bank", label: "Capital Small Finance Bank" },
    { value: "Central Bank of India", label: "Central Bank of India (CBI)" },
    { value: "Chaitanya Godavari Grameena Bank", label: "Chaitanya Godavari Grameena Bank" },
    { value: "Chhattisgarh Rajya Gramin Bank", label: "Chhattisgarh Rajya Gramin Bank" },
    { value: "Citibank", label: "Citibank" },
    { value: "City Union Bank", label: "City Union Bank" },
    { value: "CSB Bank Limited", label: "CSB Bank Limited" },
    { value: "Dakshin Bihar Gramin Bank", label: "Dakshin Bihar Gramin Bank" },
    { value: "DBS Bank India Limited", label: "DBS Bank India Limited" },
    { value: "DCB Bank", label: "DCB Bank" },
    { value: "Deutsche Bank", label: "Deutsche Bank" },
    { value: "Dhanlaxmi Bank", label: "Dhanlaxmi Bank" },
    { value: "Equitas Small Finance Bank", label: "Equitas Small Finance Bank" },
    { value: "ESAF Small Finance Bank", label: "ESAF Small Finance Bank" },
    { value: "Federal Bank", label: "Federal Bank" },
    { value: "FINO Payments Bank", label: "FINO Payments Bank" },
    { value: "HDFC Bank", label: "HDFC Bank" },
    { value: "Himachal Pradesh Gramin Bank", label: "Himachal Pradesh Gramin Bank" },
    { value: "HSBC", label: "HSBC (Hong Kong and Shanghai Banking Corporation)" },
    { value: "ICICI Bank", label: "ICICI Bank" },
    { value: "IDBI Bank Limited", label: "IDBI Bank Limited" },
    { value: "IDFC FIRST Bank Limited", label: "IDFC FIRST Bank Limited" },
    { value: "India Post Payments Bank", label: "India Post Payments Bank" },
    { value: "Indian Bank", label: "Indian Bank" },
    { value: "Indian Overseas Bank", label: "Indian Overseas Bank (IOB)" },
    { value: "IndusInd Bank", label: "IndusInd Bank" },
    { value: "Jammu & Kashmir Bank", label: "Jammu & Kashmir Bank (J&K Bank)" },
    { value: "Jana Small Finance Bank", label: "Jana Small Finance Bank" },
    { value: "Jharkhand Rajya Gramin Bank", label: "Jharkhand Rajya Gramin Bank" },
    { value: "Jio Payments Bank", label: "Jio Payments Bank" },
    { value: "Karnataka Bank", label: "Karnataka Bank" },
    { value: "Karnataka Gramin Bank", label: "Karnataka Gramin Bank" },
    { value: "Karnataka Vikas Grameena Bank", label: "Karnataka Vikas Grameena Bank" },
    { value: "Karur Vysya Bank", label: "Karur Vysya Bank (KVB)" },
    { value: "Kerala Gramin Bank", label: "Kerala Gramin Bank" },
    { value: "Kotak Mahindra Bank", label: "Kotak Mahindra Bank" },
    { value: "Madhya Pradesh Gramin Bank", label: "Madhya Pradesh Gramin Bank" },
    { value: "Madhyanchal Gramin Bank", label: "Madhyanchal Gramin Bank" },
    { value: "Maharashtra Gramin Bank", label: "Maharashtra Gramin Bank" },
    { value: "Nainital Bank", label: "Nainital Bank" },
    { value: "NSDL Payments Bank Limited", label: "NSDL Payments Bank Limited" },
    { value: "Paschim Banga Gramin Bank", label: "Paschim Banga Gramin Bank" },
    { value: "Paytm Payments Bank", label: "Paytm Payments Bank" },
    { value: "Prathama UP Gramin Bank", label: "Prathama UP Gramin Bank" },
    { value: "Puduvai Bharathiar Grama Bank", label: "Puduvai Bharathiar Grama Bank" },
    { value: "Punjab & Sind Bank", label: "Punjab & Sind Bank" },
    { value: "Punjab Gramin Bank", label: "Punjab Gramin Bank" },
    { value: "Punjab National Bank", label: "Punjab National Bank (PNB)" },
    { value: "Rajasthan Marudhara Gramin Bank", label: "Rajasthan Marudhara Gramin Bank" },
    { value: "RBL Bank", label: "RBL Bank" },
    { value: "Saptagiri Grameena Bank", label: "Saptagiri Grameena Bank" },
    { value: "Saraswat Cooperative Bank", label: "Saraswat Cooperative Bank" },
    { value: "Sarva Haryana Gramin Bank", label: "Sarva Haryana Gramin Bank" },
    { value: "SBM Bank (India) Limited", label: "SBM Bank (India) Limited" },
    { value: "Shivalik Small Finance Bank", label: "Shivalik Small Finance Bank" },
    { value: "South Indian Bank", label: "South Indian Bank" },
    { value: "Standard Chartered Bank", label: "Standard Chartered Bank" },
    { value: "State Bank of India", label: "State Bank of India (SBI)" },
    { value: "Suryoday Small Finance Bank", label: "Suryoday Small Finance Bank" },
    { value: "Tamil Nadu Grama Bank", label: "Tamil Nadu Grama Bank" },
    { value: "Tamilnad Mercantile Bank", label: "Tamilnad Mercantile Bank" },
    { value: "Telangana Grameena Bank", label: "Telangana Grameena Bank" },
    { value: "UCO Bank", label: "UCO Bank" },
    { value: "Ujjivan Small Finance Bank", label: "Ujjivan Small Finance Bank" },
    { value: "Union Bank of India", label: "Union Bank of India" },
    { value: "Unity Small Finance Bank", label: "Unity Small Finance Bank" },
    { value: "Uttar Bihar Gramin Bank", label: "Uttar Bihar Gramin Bank" },
    { value: "Uttarakhand Gramin Bank", label: "Uttarakhand Gramin Bank" },
    { value: "Uttarbanga Kshetriya Gramin Bank", label: "Uttarbanga Kshetriya Gramin Bank" },
    { value: "Utkal Grameen Bank", label: "Utkal Grameen Bank" },
    { value: "Vidharbha Konkan Gramin Bank", label: "Vidharbha Konkan Gramin Bank" },
    { value: "YES Bank", label: "YES Bank" },
    { value: "Others", label: "Others (Specify Manually)" },
].sort((a, b) => a.label.localeCompare(b.label));
